<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Reference -->
    <gazebo reference="laser_frame">
        <sensor name='gpu_lidar' type='gpu_lidar'>"
            <lidar>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <resolution>1</resolution>
                        <min_angle>-3.141592</min_angle>
                        <max_angle>3.141592</max_angle>
                    </horizontal>
                    <vertical>
                        <samples>1</samples>
                        <resolution>0.01</resolution>
                        <min_angle>0</min_angle>
                        <max_angle>0</max_angle>
                    </vertical>
                </scan>
                <range>
                    <min>0.08</min>
                    <max>10.0</max>
                    <resolution>0.01</resolution>
                </range>
            </lidar>
            <topic>scan</topic>
            <update_rate>5</update_rate>
            <always_on>1</always_on>
            <visualize>true</visualize>
            <gz_frame_id>laser_frame</gz_frame_id>
        </sensor>    
    </gazebo>

    <gazebo reference="camera_link">
        <sensor name='camera' type='camera'>
            <pose>0 0 0 0 0 0</pose>
            <visualize>true</visualize>
            <update_rate>30</update_rate>

            <camera>
                <camera_info_topic>camera/camera_info</camera_info_topic>
                <horizontal_fov>1.089</horizontal_fov>
                <image>
                    <format>R8G8B8</format>
                    <width>640</width>
                    <height>480</height>
                </image>
                <clip>
                    <near>0.05</near>
                    <far>8.0</far>
                </clip>
            </camera>

            <topic>camera/image_raw</topic>
            <gz_frame_id>camera_optical_link</gz_frame_id>
        </sensor>
    </gazebo>

    <gazebo>
        <plugin
            filename="libignition-gazebo-diff-drive-system.so"
            name="ignition::gazebo::systems::DiffDrive">
            <left_joint>base_TO_left_wheel</left_joint>
            <right_joint>base_TO_right_wheel</right_joint>
            <wheel_separation>${chasis_l_y + wheel_width}</wheel_separation>
            <wheel_radius>${wheel_radius}</wheel_radius>
            <odom_publish_frequency>1</odom_publish_frequency>
            <topic>cmd_vel</topic>
        </plugin>

        <plugin filename="libignition-gazebo6-joint-state-publisher-system.so" name="ignition::gazebo::systems::JointStatePublisher">
            <!-- Yayınlama frekansı (Hz) -->
            <update_rate>50</update_rate>
            <!-- Yayınlanacak eklemlerin listesi -->
            <joint_names>
                <joint>base_TO_left_wheel</joint>
                <joint>base_TO_right_wheel</joint>
                <!-- Diğer eklemleri de ekleyebilirsiniz -->
            </joint_names>
        </plugin>

        <plugin
            filename="gz-sim-sensors-system"
            name="gz::sim::systems::Sensors">
            <render_engine>ogre2</render_engine>
        </plugin>

    </gazebo>

</robot>
